apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-phpfpm
  namespace: myapp
  labels:
    app: nginx-phpfpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-phpfpm
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      containers:
      - name: nginx-phpfpm
        # run: minikube image load hands-on:v1
        image: docker.io/library/hands-on:v1
        # only for minikube, otherwise use: IfNotPresent
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          successThreshold: 1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm-service
  namespace: myapp
spec:
  selector:
    app: nginx-phpfpm
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
